//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Shop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BanHangOnlineEntities : DbContext
    {
        public BanHangOnlineEntities()
            : base("name=BanHangOnlineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<baiViet> baiViet { get; set; }
        public virtual DbSet<ctDonHang> ctDonHang { get; set; }
        public virtual DbSet<donHang> donHang { get; set; }
        public virtual DbSet<khachHang> khachHang { get; set; }
        public virtual DbSet<loaiSP> loaiSP { get; set; }
        public virtual DbSet<quanHuyen> quanHuyen { get; set; }
        public virtual DbSet<sanPham> sanPham { get; set; }
        public virtual DbSet<taiKhoanTV> taiKhoanTV { get; set; }
    }
}
